#!/usr/bin/env bash
if ! command -v brew &>/dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew tap homebrew/cask-versions
brew tap homebrew/cask-fonts
brew install \
	git gh exa bat ranger btop fzf \
	lolcat thefuck neofetch \
	nvim \
	spotify spotify-tui spotifyd \
	zoom slack obsidian discord-canary \
	brave-browser 1password raycast \
	font-hack

if ! command -v yabai &>/dev/null; then
	echo -e "\n (!) Yabai installation requires partially disabling SIP.\n     Install manually: https://github.com/koekeishiya/yabai\n"
fi
