#!/usr/bin/env bash

set -euo pipefail

if ! command -v brew &>/dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew tap homebrew/cask-versions
brew tap homebrew/cask-fonts

# Read the list of packages from brew_leaves
IFS=$'\n' read -d '' -r -a LEAVES <brew_leaves

echo "About to install the following packages:"
echo "${LEAVES[@]}"
read -p "Continue? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
	exit 1
fi

brew install --dry-run "${LEAVES[@]}"

# Read the list of casks from brew_casks
IFS=$'\n' read -d '' -r -a CASKS <brew_casks

echo "About to install the following casks:"
echo "${CASKS[@]}"
read -p "Continue? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
	exit 1
fi

brew install --dry-run "${CASKS[@]}"

if ! command -v yabai &>/dev/null; then
	echo -e "\n (!) Yabai installation requires partially disabling SIP.\n     Install manually: https://github.com/koekeishiya/yabai\n"
fi
