#!/usr/bin/env sh
if ! command -v brew &> /dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi


brew install git gh wget htop tree lolcat thefuck neofetch

brew install kitty fish koekeishiya/formulae/skhd

brew install nvim visual-studio-code

echo "\n -=-=-=-=-=-=-=-=-=-=-=-=-=-=- \n" | lolcat

brew install spotify spotify-tui spotifyd

brew install zoom clickup

brew install ubersicht
git clone https://github.com/AlexMeuer/simple-bar.git $HOME/Library/Application\ Support/Übersicht/widgets/simple-bar

brew install raycast

brew tap homebrew/cask-fonts
brew install font-fira-code font-hack font-mononoki

brew tap homebrew/cask-versions
brew install discord-canary

echo "\n -=-=-=-=-=-=-=-=-=-=-=-=-=-=- " | lolcat

if command -v go &> /dev/null; then
    echo "\n :)  Go already installed." | lolcat
else
    echo "\n (!) Go not installed. Install manually."
fi
if command -v flutter &> /dev/null; then
    echo "\n :)  Flutter already installed." | lolcat
else
    echo "\n (!) Flutter not installed. Install manually."
fi

if command -v node &> /dev/null; then
    echo "\n :)  Node already installed." | lolcat
else
    echo "\n (!) Node not installed. Install with 'brew install node'."
fi

if ! command -v yabai &> /dev/null; then
    echo "\n (!) Yabai installation requires partially disabling SIP.\n     Install manually: https://github.com/koekeishiya/yabai\n"
fi
