#!/usr/bin/env bash
DIR="$(git rev-parse --show-toplevel)"

linkIfNotExists() {
	if [ $# -lt 1 ]; then
		echo "developer error: cannot link without any arguments"
		exit 1
	fi
	LINK_TO="${DIR}/${1}"
	LINK_FROM="${HOME}/${2:-$1}"
	if [ -f "${LINK_FROM}" ] || [ -d "${LINK_FROM}" ]; then
		echo "Won't link ${LINK_FROM} because it already exists."
		return 1
	else
		echo "Linking ${LINK_FROM}"
		ln -s "${LINK_TO}" "${LINK_FROM}"
		return 0
	fi
}

linkIfNotExists ".config/fish"
linkIfNotExists ".config/kitty"
linkIfNotExists ".config/nvim"
linkIfNotExists ".config/ranger"
linkIfNotExists ".config/sketchybar"
linkIfNotExists ".config/nap"

linkIfNotExists "mac/.yabairc" ".yabairc"
linkIfNotExists "mac/.skhdrc" ".skhdrc"

yabai --restart-service
skhd --restart-service
brew services restart sketchybar
