#!/usr/bin/env sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
ln -s ${DIR}/mac/.yabairc ${HOME}/.yabairc
ln -s ${DIR}/mac/.skhdrc ${HOME}/.skhdrc
ln -s ${DIR}/.config/nvim ${HOME}/.config/nvim
ln -s ${DIR}/.config/kitty ${HOME}/.config/kitty

brew services restart yabai
brew services restart skhd
