#! /bin/sh

dunst &
pipewire &
pipewire-pulse &
sxhkd &
polybar &

feh --bg-fill --randomize --recursive $HOME/Pictures/wallpaper/ &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#6e738d'
bspc config active_border_color  '#f5a97f'
bspc config focused_border_color '#f5a97f'

bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a notion desktop='^4'
