#! /bin/sh

dunst &
pipewire &
sxhkd &
polybar &

feh --bg-fill --randomize --recursive $HOME/Pictures/wallpaper/ &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#6272a4'
bspc config active_border_color  '#f1fa8c'
bspc config focused_border_color '#ffb86c'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
