#!/bin/sh
# Description: Clone a GitHub repo to ~/repos/<user>/<repo>
# Usage: clone <user>/<repo> [git flags...]
# Example: clone johndoe/myrepo
# Example: clone johndoe/myrepo --bare

set -e

if ! command -v gh > /dev/null; then
    printf "gh command not found\n"
    exit 1
fi

if [ -z "$1" ]; then
    printf "Usage: %s <user>/<repo>\n" "${0}"
    exit 1
fi

SLUG="$1"
shift
USER=$(echo "$SLUG" | cut -d/ -f1)
REPO=$(echo "$SLUG" | cut -d/ -f2)

mkdir -p "${HOME}/repos/${USER}"

REPO_PATH="${HOME}/repos/${USER}/${REPO}"

if [ -d "${HOME}/repos/${USER}/${REPO}" ]; then
    printf "Repo already exists\n"
    exit 1
fi


gh repo clone "${SLUG}" "${REPO_PATH}" -- "$@"

printf "Repo cloned to %s\n" "${REPO_PATH}"
