#!/bin/sh
REMOTE=$(git remote | grep -m1 '^origin$' || git remote | head -1)
BRANCH=$(git symbolic-ref "refs/remotes/$REMOTE/HEAD" 2>/dev/null | sed "s@^refs/remotes/$REMOTE/@@")
if [ -z "$BRANCH" ]; then
    BRANCH=$(git remote show "$REMOTE" | awk '/HEAD branch/ {print $NF}')
fi
exec git switch "$BRANCH"
