#!/bin/bash

if [ -z "$1" ]; then
	printf "\e[36mOpen the selected file on github\n"
	printf "\e[37mAssumes the file is in the main branch.\n"
	printf "Works from any subdirectory of the repo.\n"
	printf "\e[92mUsage:  \e[0m \e[93m%s <file_path>\e[0m\n" "$(basename "${0}")"
	exit 1
fi

open "$(ghurl "$1")"
