#!/bin/sh
if [ $# -ne 1 ]
  then
    echo "New Remote Branch"
    echo "Creates a new branch and pushes it to the 'origin' remote."
    echo "Usage: nrbranch <BRANCH_NAME>"
    exit 1
fi
git checkout -b "${1}" && git push --set-upstream origin "${1}"
exit $?
