#!/usr/bin/env sh

STEM="ShoutCo/Off-The-Court"

gh repo clone "${STEM}-Api" && \
     gh repo clone "${STEM}-Manage" && \
     gh repo clone "${STEM}-Static" && \
     gh repo clone "${STEM}-Web" && \
     gh repo clone "${STEM}-Firebase" || \
     echo "Failed :("
